name: fortexx_signalr - TST Build

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, TST]
    environment: TST

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: dotnet restore
        run: dotnet restore
        working-directory: SignalRApp

      - name: dotnet build
        run: dotnet build --configuration Release --no-restore
        working-directory: SignalRApp

      - name: dotnet publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: SignalRApp

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signalr_tst
          path: SignalRApp/publish
          retention-days: 30
